import type { VarietyGuide } from "./learn";

/** 品種一覧ページでのグループ表示用 */
export const CULTIVAR_GROUPS = [
  {
    id: "foundation",
    label: "基礎系統",
    lead: "多くの品種の「親」となる古い系統。Typica と Bourbon から世界中の cultivar が派生しています。",
  },
  {
    id: "dwarf",
    label: "矮性・突然変異",
    lead: "ブルボンなどから生まれたコンパクトな品種。高密度栽培と収量向上に貢献しました。",
  },
  {
    id: "brazil",
    label: "ブラジル系交配",
    lead: "ブラジルで開発・普及した高収量品種。日常飲みからスペシャルティまで幅広く使われます。",
  },
  {
    id: "kenya",
    label: "ケニア・東アフリカ選抜",
    lead: "Scott Labs などで選抜された東アフリカの代表品種。複雑な酸味で知られます。",
  },
  {
    id: "central-america",
    label: "中央アメリカ",
    lead: "エルサルバドル・ニカラグアなどで育った交配・突然変異品種。",
  },
  {
    id: "colombia",
    label: "コロンビア開発",
    lead: "Cenicafé が開発した品種群。病害耐性と杯質のバランスが研究テーマです。",
  },
  {
    id: "resistance",
    label: "病害耐性（Catimor / Sarchimor 系）",
    lead: "ティモール種の遺伝子を利用した耐性品種。収量と安定性を重視した栽培向け。",
  },
  {
    id: "ethiopian",
    label: "エチオピア・在来種",
    lead: "アラビカの原産地に残る多様な土地系統。近年は中南米でも「Ethiopian-derived」として栽培。",
  },
  {
    id: "asia",
    label: "インド・インドネシア",
    lead: "アジアの伝統栽培地で育った品種。スパイス感やコクのある味わいが特徴。",
  },
  {
    id: "regional-heirloom",
    label: "地域在来種",
    lead: "特定の国・地域で長年受け継がれる在来品種群。テロワールと深く結びついています。",
  },
  {
    id: "robusta-cultivar",
    label: "ロブスタ系品種",
    lead: "ロブスタ種（Canephora）の栽培品種。エスプレッソやインスタント向けに使われます。",
  },
] as const;

export type CultivarGroupId = (typeof CULTIVAR_GROUPS)[number]["id"];

const speciesAndType: VarietyGuide[] = [
  {
    slug: "arabica",
    name_ja: "アラビカ種",
    category: "species",
    summary: "世界のスペシャルティコーヒーの約7割を占める主流種",
    description:
      "アラビカ種（Coffea arabica）はエチオピア原産で、現在のスペシャルティコーヒーの大部分を占めます。標高1000m以上の高地で栽培されることが多く、複雑で繊細な風味が特徴です。カフェイン含有量はロブスタ種より低めです。",
    characteristics: [
      "複雑で繊細な風味",
      "酸味が明るく、フルーティーな傾向",
      "標高1000m以上の高地で栽培",
      "カフェイン含有量は低め（1.2〜1.5%）",
    ],
    flavor_notes: ["フルーティー", "フローラル", "チョコレート", "ナッツ", "スパイス"],
  },
  {
    slug: "robusta",
    name_ja: "ロブスタ種",
    category: "species",
    summary: "コクと苦味が強く、エスプレッソブレンドに使われる",
    description:
      "ロブスタ種（Coffea canephora）は低地でも栽培可能で、病害に強い特性があります。アラビカ種よりカフェイン含有量が高く（2.2〜2.7%）、コクと苦味が強いのが特徴です。主にインスタントコーヒーやエスプレッソのブレンドに使われます。",
    characteristics: [
      "コクと苦味が強い",
      "カフェイン含有量が高い",
      "低地でも栽培可能で収量が多い",
      "エスプレッソブレンドやインスタントに使用",
    ],
    flavor_notes: ["ビター", "ナッツ", "穀物", "土", "ダークチョコ"],
    aliases: ["ロブスタ種", "コンイロン（Robusta）"],
  },
  {
    slug: "single-origin",
    name_ja: "シングルオリジン",
    category: "type",
    summary: "単一産地の豆だけを使用。産地の個性がストレートに楽しめる",
    description:
      "シングルオリジン（Single Origin）とは、単一の産地・農園・収穫ロットから得られたコーヒー豆のみを使用したコーヒーのことです。産地や精製方法の個性がストレートに表現され、テロワール（風土）の違いを味わえるのが魅力です。",
    characteristics: [
      "産地・農園の個性がはっきり表れる",
      "風土（テロワール）の違いを比較できる",
      "浅煎り〜中煎りで個性を楽しむことが多い",
      "季節や収穫年で味わいが変わる",
    ],
    flavor_notes: ["産地固有の風味", "季節感", "個性"],
  },
  {
    slug: "blend",
    name_ja: "ブレンド",
    category: "type",
    summary: "複数産地の豆を組み合わせ、バランスの取れた味わいを設計",
    description:
      "ブレンド（Blend）とは、複数の産地や品種のコーヒー豆を組み合わせて作られたコーヒーのことです。各豆の長所を活かし、弱点を補い合うことで、安定した味わいや特定の味の方向性を実現します。",
    characteristics: [
      "複数産地の豆を組み合わせて設計",
      "安定した味わいと再現性",
      "エスプレッソや深煎りで使われることが多い",
      "ロースターの意図や個性が反映される",
    ],
    flavor_notes: ["バランス", "安定感", "ロースターの個性"],
  },
];

const cultivars: VarietyGuide[] = [
  {
    slug: "typica-bourbon",
    name_ja: "ティピカ・ブルボン（概説）",
    category: "cultivar",
    group: "foundation",
    summary: "アラビカ種の2大基礎系統。世界中の品種の多くがここから派生",
    description:
      "ティピカ（Typica）とブルボン（Bourbon）は、アラビカ種の中でも最も古く広い系統です。Typica は繊細でフローラル、Bourbon は甘みとコクに優れ、Caturra・Catuai・SL28 など改良品種の親系統となっています。",
    characteristics: [
      "アラビカ栽培の2大基礎系統",
      "多くの改良品種・交配品種の親",
      "ティピカ：繊細・低収量、ブルボン：甘み・コク",
      "中南米・東アフリカ・インドで広く栽培",
    ],
    flavor_notes: ["ティピカ：繊細・フローラル", "ブルボン：甘み・コク"],
    parent_lineage: "エチオピア原産系統から也門経由で世界に広がった2系統",
    regions: ["中南米", "東アフリカ", "インド", "インドネシア"],
    aliases: [],
  },
  {
    slug: "typica",
    name_ja: "ティピカ（Typica）",
    category: "cultivar",
    group: "foundation",
    summary: "最古級のアラビカ系統。繊細でフローラルな風味",
    description:
      "17世紀に也門から広まった Typica 系統は、ジャワ種・ブルーマウンテン・コナなど各地の伝統栽培の基礎です。収量は低く病害に弱いものの、高標高では非常に繊細な杯質を示します。",
    characteristics: [
      "古くから広まった基礎系統",
      "収量が低く、コーヒーさびに弱い",
      "高標高で繊細・フローラルな杯質",
      "Maragogipe などの突然変異の親",
    ],
    flavor_notes: ["フローラル", "シトラス", "ナッツ", "クリーン", "繊細"],
    parent_lineage: "エチオピア原産 → 也門 → 世界各地",
    regions: ["インドネシア", "ジャマイカ", "ハワイ", "ペルー", "メキシコ"],
    aliases: ["ティピカ（Typica）"],
  },
  {
    slug: "red-bourbon",
    name_ja: "レッドブルボン（Red Bourbon）",
    category: "cultivar",
    group: "foundation",
    summary: "甘みとコクの代表系統。Caturra や Pacas の親",
    description:
      "18世紀にレユニオン（旧ブルボン島）から広まった赤実型の Bourbon 系統です。中南米・東アフリカで主力品種となり、Caturra・Pacas・Catuai など多くの派生品種の基礎となりました。",
    characteristics: [
      "甘みとコクに優れる",
      "収量は Typica より高い",
      "コーヒーさび・CBD に弱い",
      "Yellow Bourbon（黄実型）と並ぶ基本系統",
    ],
    flavor_notes: ["甘み", "キャラメル", "チョコレート", "ナッツ", "コク"],
    parent_lineage: "Bourbon（レユニオン島原産）",
    regions: ["ブラジル", "ルワンダ", "ブルンジ", "コロンビア", "エルサルバドル"],
    aliases: ["ボルボン（Bourbon）"],
  },
  {
    slug: "caturra",
    name_ja: "カトゥーラ（Caturra）",
    category: "cultivar",
    group: "dwarf",
    summary: "ブルボンの矮性突然変異。中南米の小規模農家の主力",
    description:
      "1910年代、ブラジルで Bourbon から発見された自然突然変異です。矮性で高密度栽培が可能になり、コロンビアをはじめ中南米全域に普及しました。Castillo など Catimor 系の親にもなっています。",
    characteristics: [
      "Bourbon の1遺伝子矮性突然変異",
      "高密度植栽・収量向上",
      "杯質は良好だがコーヒーさびに非常に弱い",
      "中南米の小規模農家で広く栽培",
    ],
    flavor_notes: ["明るい酸味", "柑橘", "キャラメル", "ナッツ", "クリーン"],
    parent_lineage: "Bourbon（自然突然変異）",
    regions: ["コロンビア", "コスタリカ", "グアテマラ", "ホンジュラス", "ブラジル"],
    aliases: ["カトゥーラ（Caturra）"],
  },
  {
    slug: "pacas",
    name_ja: "パカス（Pacas）",
    category: "cultivar",
    group: "dwarf",
    summary: "エルサルバドル発見の Bourbon 矮性種。Pacamara の親",
    description:
      "1949年、エルサルバドルで Bourbon から発見された矮性突然変異です。Caturra の中央アメリカ版とも言われ、Pacamara の親系統の一つでもあります。",
    characteristics: [
      "Bourbon の矮性突然変異",
      "高密度栽培に適する",
      "Central America 標準の杯質",
      "コーヒーさびに弱い",
    ],
    flavor_notes: ["キャラメル", "チョコレート", "ナッツ", "甘み", "バランス"],
    parent_lineage: "Bourbon（自然突然変異）",
    regions: ["エルサルバドル", "ホンジュラス"],
    aliases: ["パカス（Pacas）"],
  },
  {
    slug: "pache",
    name_ja: "パチェ（Pache）",
    category: "cultivar",
    group: "dwarf",
    summary: "Typica の矮性突然変異。グアテマラの標高産地で栽培",
    description:
      "グアテマラのパチェ・サンタ・ルシア地区で Typica から発見された矮性突然変異です。標高の高い産地で栽培され、繊細な風味が期待できます。",
    characteristics: [
      "Typica の矮性突然変異",
      "高標高産地向き",
      "収量は低め",
      "コーヒーさびに弱い",
    ],
    flavor_notes: ["チョコレート", "ナッツ", "穏やかな酸味", "クリーン"],
    parent_lineage: "Typica（自然突然変異）",
    regions: ["グアテマラ", "ホンジュラス", "ペルー", "パナマ"],
    aliases: ["パチェ（Pache）"],
  },
  {
    slug: "villa-sarchi",
    name_ja: "ヴィラ・サルチ（Villa Sarchi）",
    category: "cultivar",
    group: "dwarf",
    summary: "コスタリカ発見の Bourbon 矮性種。Sarchimor の親",
    description:
      "1950〜60年代、コスタリカで Bourbon から発見された矮性突然変異です。強風・高標高に適応し、Timor Hybrid との交配から Sarchimor（Parainema、Obatã 等）が生まれました。",
    characteristics: [
      "Bourbon の矮性突然変異",
      "高標高・強風に適応",
      "Sarchimor 系の親系統",
      "コーヒーさびに弱い",
    ],
    flavor_notes: ["キャラメル", "チョコレート", "シトラス", "甘み"],
    parent_lineage: "Bourbon（自然突然変異）",
    regions: ["コスタリカ", "ホンジュラス"],
    aliases: ["ヴィラ・サルチ（Villa Sarchi）"],
  },
  {
    slug: "mundo-novo",
    name_ja: "ムンドノーヴォ（Mundo Novo）",
    category: "cultivar",
    group: "brazil",
    summary: "Typica×Bourbon の自然雑種。ブラジル最大級の基幹品種",
    description:
      "1943年、ブラジルで Typica と Red Bourbon の自然雑交から発見されました。高収量と安定した杯質でブラジル商業栽培の基盤となり、Catuai など後続品種の親にもなっています。",
    characteristics: [
      "非常に高い収量",
      "高木（tall stature）",
      "コーヒーさび・ベリー病に弱い",
      "800〜1400m で安定した品質",
    ],
    flavor_notes: ["ナッツ", "チョコレート", "キャラメル", "甘み", "フルボディ"],
    parent_lineage: "Typica × Bourbon（自然雑種）",
    regions: ["ブラジル", "ペルー", "メキシコ"],
    aliases: ["ムンドノーヴォ（Mundo Novo）"],
  },
  {
    slug: "catuai",
    name_ja: "カトゥアイ（Catuaí）",
    category: "cultivar",
    group: "brazil",
    summary: "Caturra×Mundo Novo の交配。ブラジルを中心に普及した矮性高収量品種",
    description:
      "1949年に IAC（ブラジル）が Yellow Caturra と Mundo Novo を交配し、1972年にリリースされました。矮性で高密度栽培・機械収穫に適し、赤実（Red）と黄実（Yellow）の系統があります。",
    characteristics: [
      "矮性で高密度植栽向き",
      "収量が高い",
      "コーヒーさび・ベリー病に弱い",
      "肥料管理を要する",
    ],
    flavor_notes: ["ナッツ", "チョコレート", "キャラメル", "バランス", "甘み"],
    parent_lineage: "Yellow Caturra × Mundo Novo",
    regions: ["ブラジル", "ホンジュラス", "コスタリカ", "ハワイ"],
    aliases: ["カトゥアイ（Catuaí）", "カトゥアイ（Catuai）"],
  },
  {
    slug: "arara",
    name_ja: "アララ（Arara）",
    category: "cultivar",
    group: "brazil",
    summary: "ブラジル Procafé 登録。病害耐性と杯質を両立する自然雑交品種",
    description:
      "Obatã（Sarchimor 系）と Catuai Amarelo の自然雑交から発見され、2012年に Fundação Procafé が商業リリースしました。Timor 系遺伝子によるさび耐性を持ちながら、従来の Sarchimor 系より杯質が高いと評価されています。",
    characteristics: [
      "コーヒーさびに強い（Timor 系遺伝子）",
      "高収量・矮性・大粒果実",
      "遅熟で収穫期の分散に有用",
      "スペシャルティでも甘み・フローラルの評価例あり",
    ],
    flavor_notes: ["フローラル", "キャラメル", "シトラス", "甘み", "ココナッツ"],
    parent_lineage: "Obatã × Catuai Amarelo（自然雑交）",
    aliases: ["アララ種", "アララ（Arara）"],
  },
  {
    slug: "sl28",
    name_ja: "SL28",
    category: "cultivar",
    group: "kenya",
    summary: "ケニア Scott Labs 選抜の伝説的品種。ブラックカラント感で知られる",
    description:
      "1930年代後半、ケニアの Scott Agricultural Laboratories で耐旱性品種から選抜されました。複雑な酸味とブラックカラントのような風味で世界的評価を得ていますが、CBD・さびに非常に弱いです。",
    characteristics: [
      "卓越したカップ品質",
      "耐旱性に優れる",
      "コーヒーベリー病（CBD）に非常に弱い",
      "コーヒーさびにも弱い",
    ],
    flavor_notes: ["ブラックカラント", "トマト", "ワイン", "ベリー", "複雑な酸味"],
    parent_lineage: "Tanganyika Drought Resistant 選抜（Bourbon 系に関連）",
    regions: ["ケニア", "ウガンダ", "タンザニア"],
    aliases: ["SL14・SL28"],
  },
  {
    slug: "sl34",
    name_ja: "SL34",
    category: "cultivar",
    group: "kenya",
    summary: "ケニア Scott Labs 選抜。SL28 と並ぶ高品質品種",
    description:
      "1935〜1939年頃、ケニア・Kabete の French Mission 木から選抜されました。SL28 と並ぶケニア高品質品種の代表ですが、CBD に非常に弱い点も共通しています。",
    characteristics: [
      "卓越したカップ品質",
      "SL28 と並ぶケニア代表品種",
      "CBD に非常に弱い",
      "コーヒーさびにも弱い",
    ],
    flavor_notes: ["ブラックカラント", "ベリー", "シトラス", "ワイン", "ボディ"],
    parent_lineage: "French Mission 選抜（Bourbon 系）",
    regions: ["ケニア"],
    aliases: ["SL34"],
  },
  {
    slug: "ruiru-11",
    name_ja: "ルイリ11（Ruiru 11）",
    category: "cultivar",
    group: "kenya",
    summary: "ケニア開発の F1 複雑雑種。矮性・病害耐性・高収量",
    description:
      "1968年の CBD 大流行を契機に、ケニア・Ruiru 研究ステーションで開発され1985年にリリースされました。SL28・SL34 などと Catimor 系を組み合わせた F1 ハイブリッドです。",
    characteristics: [
      "矮性で高密度栽培可能",
      "CBD・コーヒーさび耐性",
      "F1 ハイブリッド vigor による高収量",
      "カップ品質は SL28/SL34 より評価が分かれる",
    ],
    flavor_notes: ["ブラックカラント", "ベリー", "シトラス", "スパイス", "ボディ"],
    parent_lineage: "複雑雑種♂ × Catimor♀",
    regions: ["ケニア"],
    aliases: ["ルイ11（Ruiru 11）"],
  },
  {
    slug: "batian",
    name_ja: "バティアン（Batian）",
    category: "cultivar",
    group: "kenya",
    summary: "2010年リリースのケニア複合品種。Ruiru 11 の後継",
    description:
      "Ruiru 11 の♂親系統を5世代自家交配で固定化し、2010年にリリースされました。CBD・さび耐性を保ちつつ、SL28 に近いカップ品質の回復を目指して開発されました。",
    characteristics: [
      "CBD・コーヒーさびに耐性",
      "Ruiru 11 より品質の再現性が高い",
      "SL28 に近い系統を含む",
      "ケニアの病害対策主力品種",
    ],
    flavor_notes: ["ブラックカラント", "ベリー", "シトラス", "ワイン", "スパイス"],
    parent_lineage: "Ruiru 11 ♂系統の F5 選抜",
    regions: ["ケニア"],
    aliases: ["バティアン（Batian）"],
  },
  {
    slug: "bourbon-mayaguez",
    name_ja: "ブルボン・マヤゲス（Bourbon Mayaguez）",
    category: "cultivar",
    group: "kenya",
    summary: "東アフリカで選抜された Bourbon 系統。ルワンダ・ブルンジの基盤",
    description:
      "プエルトリコ・マヤゲスの USDA 種子バンク経由でコンゴに導入され、1950年代にルワンダへ広がった Bourbon 選抜系統です。BM71 と BM139 が主要系統で、東アフリカスペシャルティの基盤となっています。",
    characteristics: [
      "中程度の収量・良好な杯質",
      "中標高に適応",
      "主要病害に感受性",
      "ルワンダ・ブルンジの主力",
    ],
    flavor_notes: ["ベリー", "シトラス", "紅茶", "キャラメル", "フローラル"],
    parent_lineage: "Bourbon（Puerto Rico Mayaguez 経由）",
    regions: ["ルワンダ", "ブルンジ", "コンゴ", "タンザニア"],
    aliases: [],
  },
  {
    slug: "jackson",
    name_ja: "ジャバ（Jackson）",
    category: "cultivar",
    group: "kenya",
    summary: "インド発の Typica 選抜。東アフリカでも栽培",
    description:
      "20世紀初頭、インドで Typica から選抜された系統で、タンザニア・ブルンジなど東アフリカにも導入されました。Bourbon Mayaguez と並ぶ東アフリカの伝統品種の一つです。",
    characteristics: [
      "Typica 選抜系統",
      "中程度の収量",
      "病害に感受性",
      "東アフリカの伝統栽培",
    ],
    flavor_notes: ["紅茶", "ベリー", "シトラス", "キャラメル"],
    parent_lineage: "Typica 選抜（インド）",
    regions: ["ブルンジ", "ルワンダ", "タンザニア"],
    aliases: ["ジャバ（Jackson）"],
  },
  {
    slug: "pacamara",
    name_ja: "パカマラ（Pacamara）",
    category: "cultivar",
    group: "central-america",
    summary: "Pacas×Maragogipe 交配。大粒豆と個性的なカップ",
    description:
      "1958年にエルサルバドル咖啡研究所（ISIC）が Pacas と Maragogipe を人工交配し開発しました。Cup of Excellence で高評価を受けるエルサルバドル代表品種です。",
    characteristics: [
      "大粒豆（エレファントビーンに近い）",
      "高標高で卓越した杯質の可能性",
      "非均一（形質が完全安定しない）",
      "コーヒーさびに非常に弱い",
    ],
    flavor_notes: ["ハーブ", "フローラル", "シトラス", "ワイン", "トロピカルフルーツ"],
    parent_lineage: "Pacas × Maragogipe",
    regions: ["エルサルバドル", "グアテマラ", "ホンジュラス", "ニカラグア"],
    aliases: ["パカマラ（Pacamara）"],
  },
  {
    slug: "maragogipe",
    name_ja: "マラゴジペ（Maragogipe）",
    category: "cultivar",
    group: "central-america",
    summary: "Typica の巨大型突然変異。通称「エレファントビーン」",
    description:
      "1870年頃、ブラジルで Typica から発見された自然突然変異です。異常に大きな豆・葉・枝間隔（gigas form）が特徴で、Pacamara などの交配親として使われることが多いです。",
    characteristics: [
      "異常に大きな豆・葉",
      "収量が非常に低い",
      "高標高では良好な杯質",
      "コーヒーさびに非常に弱い",
    ],
    flavor_notes: ["シトラス", "フローラル", "ハチミツ", "ナッツ", "クリーン"],
    parent_lineage: "Typica（自然突然変異）",
    regions: ["ブラジル", "エルサルバドル", "ニカラグア", "グアテマラ"],
    aliases: [],
  },
  {
    slug: "maracaturra",
    name_ja: "マラカトゥーラ（Maracaturra）",
    category: "cultivar",
    group: "central-america",
    summary: "Caturra×Maragogipe の自然雑交。ニカラグア発",
    description:
      "1976年ニカラグア INTA が Caturra × Maragogipe の自然雑交から選択開始しました。公式安定化は未完了ですが、Central America の個人農園で栽培が続いています。",
    characteristics: [
      "大粒豆",
      "非安定（均一性低い）",
      "高いカップ品質の可能性",
      "病害に弱い",
    ],
    flavor_notes: ["シトラス", "フローラル", "ベリー", "ハチミツ", "複雑"],
    parent_lineage: "Caturra × Maragogipe（自然雑交）",
    regions: ["ニカラグア", "コスタリカ", "ホンジュラス"],
    aliases: ["マラカトゥーラ（Maracaturra）"],
  },
  {
    slug: "castillo",
    name_ja: "カスティージョ（Castillo）",
    category: "cultivar",
    group: "colombia",
    summary: "コロンビア Cenicafé 開発の Catimor 複合品種",
    description:
      "Caturra × Timor Hybrid の5世代選択により2005年にリリースされた複合品種です。6つの地域別系統があり、2008年以降の大規模更新プログラムでコロンビア全土に普及しました。",
    characteristics: [
      "矮性・高収量・コーヒーさび耐性",
      "複合品種（複数系統の混合）",
      "Robusta 遺伝子導入（Catimor 系）",
      "スペシャルティ市場では評価が分かれる",
    ],
    flavor_notes: ["チョコレート", "ナッツ", "キャラメル", "スパイス", "中程度のボディ"],
    parent_lineage: "Caturra × Timor Hybrid",
    regions: ["コロンビア"],
    aliases: ["カスティージョ（Castillo）"],
  },
  {
    slug: "tabi",
    name_ja: "タビ（Tabi）",
    category: "cultivar",
    group: "colombia",
    summary: "2002年リリースのコロンビア高木品種。Castillo より杯質評価が高いことが多い",
    description:
      "Cenicafé が1970年代から開発した高木（tall stature）品種で、Timor Hybrid と Typica/Bourbon 系を交配しました。Castillo より杯質評価が高いとされることが多いです。",
    characteristics: [
      "高木（shade coffee 向き）",
      "コーヒーさび耐性",
      "Castillo より高い杯質の報告",
      "収量は Caturra 系より低い",
    ],
    flavor_notes: ["シトラス", "フローラル", "キャラメル", "チョコレート", "複雑"],
    parent_lineage: "Timor Hybrid × Typica / Bourbon 系",
    regions: ["コロンビア"],
    aliases: ["タビ（Tabi）"],
  },
  {
    slug: "colombia-variedad",
    name_ja: "コロンビア（Variedad Colombia）",
    category: "cultivar",
    group: "colombia",
    summary: "1982年リリースの Catimor 複合品種。Castillo の前身",
    description:
      "Caturra × Timor Hybrid から5世代選択し1982年にリリースされました。1983年のさび侵入前に普及し、Castillo 開発の基礎となりました。",
    characteristics: [
      "矮性・高収量・さび耐性",
      "Castillo より古い世代",
      "複合品種",
      "Robusta 遺伝子導入",
    ],
    flavor_notes: ["チョコレート", "ナッツ", "キャラメル", "スパイス"],
    parent_lineage: "Caturra × Timor Hybrid",
    regions: ["コロンビア"],
    aliases: [],
  },
  {
    slug: "catimor-group",
    name_ja: "カティモール系（Catimor）",
    category: "cultivar",
    group: "resistance",
    summary: "Timor Hybrid × Caturra 系の病害耐性品種群",
    description:
      "Catimor は Timor Hybrid（アラビカ×ロブスタ自然雑種）と Caturra などを交配した品種群の総称です。Castillo、Colombia、Costa Rica 95、Lempira などが含まれ、収量とさび耐性を重視した栽培に使われます。",
    characteristics: [
      "Robusta 遺伝子によるさび耐性",
      "矮性・高収量",
      "杯質は品種・管理により差が大きい",
      "新しいさびレースへの感受性が報告される例も",
    ],
    flavor_notes: ["チョコレート", "ナッツ", "穀物", "中程度のボディ"],
    parent_lineage: "Timor Hybrid × Caturra 系",
    regions: ["コロンビア", "Central America", "アジア"],
    aliases: [],
  },
  {
    slug: "ihcafe-90",
    name_ja: "IHCAFE 90",
    category: "cultivar",
    group: "resistance",
    summary: "ホンジュラス開発の Catimor 系。さび耐性と高収量",
    description:
      "Timor Hybrid 832/1 × Caturra の交配から IHCAFE が系統選択した Catimor 系品種です。1990年代にリリースされ、ホンジュラス全土に普及しました。",
    characteristics: [
      "矮性・高収量",
      "Catimor 系（Robusta 遺伝子導入）",
      "新レース出現により感受性が確認される例あり",
      "オホデガヨに弱い",
    ],
    flavor_notes: ["ナッツ", "チョコレート", "穏やかな酸味", "穀物"],
    parent_lineage: "Timor Hybrid 832/1 × Caturra",
    regions: ["ホンジュラス"],
    aliases: ["IHCAFE 90"],
  },
  {
    slug: "lempira",
    name_ja: "レンピラ（Lempira）",
    category: "cultivar",
    group: "resistance",
    summary: "1998年リリースのホンジュラス Catimor。かつて全栽培面積の45%",
    description:
      "IHCAFE 90 と同系統（Timor Hybrid 832/1 × Caturra）で、Costa Rica 95 に非常に類似します。1998年にリリースされ、2007年以降にさびの新レースにより感受性が報告されました。",
    characteristics: [
      "矮性・高収量",
      "1990〜2000年代のホンジュラス主力",
      "現在はさび感受性が確認",
      "Parainema 等への移行が進行",
    ],
    flavor_notes: ["ナッツ", "チョコレート", "穏やかな酸味", "穀物"],
    parent_lineage: "Timor Hybrid 832/1 × Caturra",
    regions: ["ホンジュラス"],
    aliases: ["レモン（Lempira）"],
  },
  {
    slug: "parainema",
    name_ja: "パライネマ（Parainema）",
    category: "cultivar",
    group: "resistance",
    summary: "ホンジュラス Sarchimor 系。Lempira 後継の耐性品種",
    description:
      "T5296（Villa Sarchi × Timor Hybrid）から IHCAFE が選択し2004年リリースされました。Lempira / IHCAFE 90 より杯質が高いとされ、SH8 さび耐性遺伝子を持ちます。",
    characteristics: [
      "Sarchimor 系・さび耐性",
      "Lempira より高い杯質評価",
      "中標高に適応",
      "根結線虫に部分的耐性",
    ],
    flavor_notes: ["シトラス", "フローラル", "キャラメル", "バランス"],
    parent_lineage: "Villa Sarchi × Timor Hybrid（T5296 選抜）",
    regions: ["ホンジュラス", "ニカラグア"],
    aliases: [],
  },
  {
    slug: "costa-rica-95",
    name_ja: "コスタリカ95（Costa Rica 95）",
    category: "cultivar",
    group: "resistance",
    summary: "Central America の Catimor 代表品種。Lempira と類似",
    description:
      "Timor Hybrid 832/1 × Caturra から CATIE が選択した Catimor 系品種です。Lempira や IHCAFE 90 と非常に類似し、Central America で広く栽培されています。",
    characteristics: [
      "矮性・高収量",
      "Catimor 系",
      "新レースで感受性報告あり",
      "商業品質",
    ],
    flavor_notes: ["ナッツ", "チョコレート", "穏やかな酸味"],
    parent_lineage: "Timor Hybrid 832/1 × Caturra",
    regions: ["コスタリカ", "Central America"],
    aliases: [],
  },
  {
    slug: "ethiopian-heirloom",
    name_ja: "エチオピア在来種（Heirloom / Landrace）",
    category: "cultivar",
    group: "ethiopian",
    summary: "エチオピア原産の在来集団。130以上の土地系統を含む総称",
    description:
      "アラビカの原産地エチオピアで栽培される在来集団の総称です。74158・74110 など JARC 選抜系統や、名前のない森咖啡の在来種が含まれ、Geisha・Sidra・Pink Bourbon などもこの系統に属すると判明した例があります。",
    characteristics: [
      "世界最大のアラビカ遺伝資源",
      "単一固定品種ではなく多様な集団",
      "地域・農家ごとに風味が大きく異なる",
      "改良品種との混交リスクあり",
    ],
    flavor_notes: ["ベリー", "フローラル", "シトラス", "紅茶", "ワイン", "複雑"],
    parent_lineage: "野生 C. arabica 系統",
    regions: ["エチオピア", "コロンビア", "パナマ", "エクアドル"],
    aliases: [
      "ヘイローム種（在来種）",
      "74158・74110・74112 など",
      "在来品種",
    ],
  },
  {
    slug: "geisha",
    name_ja: "ゲイシャ（ゲシャ）",
    category: "cultivar",
    group: "ethiopian",
    summary: "エチオピア原産の高級品種。華やかなジャスミンの香りが特徴",
    description:
      "ゲイシャ（Geisha / Gesha）種はエチオピア原産の品種で、パナマのボケテ地区で世界的な評価を得ました。非常に華やかなジャスミンの香りと、トロピカルフルーツのような複雑な風味が特徴です。",
    characteristics: [
      "エチオピア landrace 系統",
      "華やかなジャスミンの香り",
      "トロピカルフルーツのような複雑な風味",
      "標高の高い産地で個性が際立つ",
    ],
    flavor_notes: ["ジャスミン", "ベルガモット", "マンゴー", "パパイヤ", "ハチミツ"],
    parent_lineage: "Ethiopian landrace（T2722 系統）",
    regions: ["パナマ", "エチオピア", "コロンビア", "コスタリカ"],
    aliases: ["ゲイシャ（ゲシャ）", "ゲイシャ（Geisha）"],
  },
  {
    slug: "sidra",
    name_ja: "シドラ（Sidra）",
    category: "cultivar",
    group: "ethiopian",
    summary: "エクアドル発の競技向け品種。Ethiopian landrace 系",
    description:
      "1990年代、エクアドルで開発・発見されたとされ、遺伝解析では Typica×Bourbon 説は否定され Ethiopian landrace（Core Ethiopia）に分類されています。WBC など競技会で頻繁に使われます。",
    characteristics: [
      "高木・日陰栽培向き",
      "高いカップ品質（競技会で頻出）",
      "コーヒーさびに感受性",
      "1650〜1800m で最良の結果",
    ],
    flavor_notes: ["ジャスミン", "ストーンフルーツ", "ベリー", "シトラス", "ワイン"],
    parent_lineage: "Ethiopian landrace",
    regions: ["エクアドル", "コロンビア", "ペルー"],
    aliases: [],
  },
  {
    slug: "pink-bourbon",
    name_ja: "ピンクブルボン（Pink Bourbon）",
    category: "cultivar",
    group: "ethiopian",
    summary: "名称は Bourbon だが遺伝的にはエチオピア在来種。ピンク色の果実",
    description:
      "コロンビア・Huila 等で Red×Yellow Bourbon の交配と長く信じられていましたが、2023年の遺伝解析で Ethiopian landrace と判明しました。果実がサーモンピンク色なのが名称の由来です。",
    characteristics: [
      "Bourbon とは無関係（Ethiopian landrace）",
      "ピンク〜サーモン色の果実",
      "農園間で遺伝的均一性は限定的",
      "スペシャルティで高値取引",
    ],
    flavor_notes: ["ベリー", "フローラル", "シトラス", "ハチミツ", "ワイン"],
    parent_lineage: "Ethiopian landrace",
    regions: ["コロンビア", "エクアドル", "ペルー"],
    aliases: [],
  },
  {
    slug: "chiroso",
    name_ja: "チロソ（Chiroso）",
    category: "cultivar",
    group: "ethiopian",
    summary: "コロンビア発見の競技向け品種。Ethiopian landrace 系",
    description:
      "アンティオキア等で発見され、Caturra 突然変異と誤認されていましたが、遺伝解析で Ethiopian landrace と判明しました。Sidra・Pink Bourbon と同様「Ethiopian escapee」の一例です。",
    characteristics: [
      "Ethiopian landrace",
      "高いカップ品質（競技会で使用）",
      "Geisha よりボディ・甘みが強い傾向",
      "農園間で均一性は限定的",
    ],
    flavor_notes: ["フローラル", "ハーブ", "ピーチ", "レモングラス", "ハチミツ"],
    parent_lineage: "Ethiopian landrace",
    regions: ["コロンビア"],
    aliases: [],
  },
  {
    slug: "wush-wush",
    name_ja: "ウシュウシュ（Wush Wush）",
    category: "cultivar",
    group: "ethiopian",
    summary: "エチオピア・ケファ発の在来種。Geisha に匹敵する評価例",
    description:
      "エチオピア南西部・Wush Wush 地域の在来集団で、Geisha に似たフローラル・フルーティーな複雑さで知られます。コロンビア・パナマ等への移植実験も進んでいます。",
    characteristics: [
      "Ethiopian landrace",
      "Geisha 的なフローラル複雑さ",
      "移植先での再現性は環境依存",
      "スペシャルティ高値取引",
    ],
    flavor_notes: ["フローラル", "ベリー", "トロピカルフルーツ", "紅茶", "ジャスミン"],
    parent_lineage: "Ethiopian landrace（ケファ地域）",
    regions: ["エチオピア", "コロンビア", "パナマ"],
    aliases: [],
  },
  {
    slug: "typica-mejorado",
    name_ja: "ティピカ・メホラード（Typica Mejorado）",
    category: "cultivar",
    group: "ethiopian",
    summary: "名称は Typica だが Bourbon×Ethiopian 交配。Sidra の姉妹品種",
    description:
      "Sidra と同じ Nestlé 系研究施設由来とされ、遺伝解析では Bourbon × Ethiopian landrace 交配と判明しました。「Mejorado（改良）」は杯質の評価から命名されたものです。",
    characteristics: [
      "Ethiopian × Bourbon 交配",
      "Sidra の姉妹品種",
      "競技会で使用例増加",
      "高標高で個性が際立つ",
    ],
    flavor_notes: ["フローラル", "シトラス", "ベリー", "紅茶", "甘み"],
    parent_lineage: "Bourbon × Ethiopian landrace",
    regions: ["エクアドル", "コロンビア"],
    aliases: [],
  },
  {
    slug: "s795",
    name_ja: "S795（Selection 795）",
    category: "cultivar",
    group: "asia",
    summary: "インド開発の Kent×S288 交配。インドアラビカの基幹品種",
    description:
      "1940年代、インドで S288（C. liberica 遺伝子導入によるさび耐性）と Kent（Typica 選抜）を交配して開発されました。インドアラビカ生産の主要品種で、インドネシアでも広く栽培されています。",
    characteristics: [
      "高収量・安定した商業品質",
      "C. liberica 由来の SH3 さび耐性",
      "インド固有環境での感受性再評価あり",
      "インドネシアでも普及",
    ],
    flavor_notes: ["チョコレート", "ナッツ", "スパイス", "フルボディ", "キャラメル"],
    parent_lineage: "S288 × Kent",
    regions: ["インド", "インドネシア"],
    aliases: ["S795（ジャワ種）"],
  },
  {
    slug: "java-typica",
    name_ja: "ジャワ種（Java Typica）",
    category: "cultivar",
    group: "asia",
    summary: "17世紀末にジャワ島に持ち込まれた Typica 系統",
    description:
      "1696〜1699年、インド・マラバール海岸からバタヴィア（現ジャカルタ）に持ち込まれた Typica 系の種が、世界の Typica 流通の起点の一つとされます。300年以上の局所選択により独自の形質を示します。",
    characteristics: [
      "Typica 系だが長期の局所適応",
      "低収量・病害に弱い",
      "プレアンガー等の高標高産地で保存",
      "S795 等との混植も多い",
    ],
    flavor_notes: ["チョコレート", "キャラメル", "フローラル", "スパイス", "フルボディ"],
    parent_lineage: "Typica（インド→ジャワ、1690年代）",
    regions: ["インドネシア・ジャワ"],
    aliases: [],
  },
  {
    slug: "kent",
    name_ja: "ケント（Kent）",
    category: "cultivar",
    group: "asia",
    summary: "インド・マイソール発の Typica 選抜。S795 の親",
    description:
      "20世紀初頭、インドで Typica 集団から選択されました。初期のさび耐性を示したが、新レース出現で耐性は失われました。S795 の親として重要です。",
    characteristics: [
      "Typica 選抜",
      "初期さび耐性（現在は感受性）",
      "S795 の親",
      "インド伝統栽培",
    ],
    flavor_notes: ["チョコレート", "ナッツ", "スパイス", "フルボディ"],
    parent_lineage: "Typica 選抜（Mysore）",
    regions: ["インド"],
    aliases: [],
  },
  {
    slug: "blue-mountain",
    name_ja: "ブルーマウンテン（Blue Mountain）",
    category: "cultivar",
    group: "regional-heirloom",
    summary: "ジャマイカ・ブルーマウンテン地域の Typica。地域名＋品種の複合概念",
    description:
      "1728年にジャマイカに持ち込まれた Typica が、ブルーマウンテン標高1000m前後の微気候で育てられたものです。Coffee Industry Regulation Act により産地・標高・品質規格が厳格に管理されています。",
    characteristics: [
      "Typica 系・低収量",
      "標高・微気候・規格管理による高品質",
      "マイルドでバランスの取れた味わい",
      "病害に弱い",
    ],
    flavor_notes: ["ナッツ", "チョコレート", "クリーミー", "穏やかな酸味", "スイート"],
    parent_lineage: "Typica（1728年ジャマイカ移入）",
    regions: ["ジャマイカ", "台湾"],
    aliases: [
      "ブルーマウンテン（認定品種）",
      "ブルー・マウンテン（Blue Mountain）",
    ],
  },
  {
    slug: "yemen-heirloom",
    name_ja: "イエメン在来種（Yemen Heirloom）",
    category: "cultivar",
    group: "regional-heirloom",
    summary: "300年以上受け継がれるイエメンの在来品種群。モカの原風景",
    description:
      "イエメンは「モカ（Mocha）」の原産地として知られ、Jaadi・Udaini・Tufahi など数百年の栽培歴を持つ在来品種群が残っています。現代改良品種の導入は少なく、テラス栽培と在来種が風味の源泉です。",
    characteristics: [
      "300年以上の在来栽培",
      "現代品種の導入が少ない",
      "テラス栽培・低降水量に適応",
      "ワインのような複雑さ",
    ],
    flavor_notes: ["ワイン", "スパイス", "ダークチョコ", "ドライフルーツ", "深いコク"],
    parent_lineage: "也門経由で広まった Typica/Bourbon 系在来集団",
    regions: ["イエメン"],
    aliases: [
      "イエメン在来種（Heirloom）",
      "ジャディ（Jaadi）",
      "ウダイニ（Udaini）",
      "タフヒ（Tufahi）",
    ],
  },
  {
    slug: "mexico-heirloom",
    name_ja: "メキシコ在来種（Mexican Heirloom）",
    category: "cultivar",
    group: "regional-heirloom",
    summary: "チアパスなどに残る在来品種群。穏やかで複雑な風味",
    description:
      "メキシコ・チアパスなどに残る在来品種群で、有機認証の取得率が高い産地でも保存活動が活発です。Bourbon や Typica 系の在来選抜が含まれます。",
    characteristics: [
      "在来集団（固定品種ではない）",
      "有機栽培との相性が良い",
      "穏やかで複雑な風味",
      "小規模農家中心",
    ],
    flavor_notes: ["ナッツ", "チョコレート", "オレンジ", "スパイス", "穏やか"],
    parent_lineage: "Typica / Bourbon 系在来集団",
    regions: ["メキシコ"],
    aliases: ["メキシコ在来種（Heirloom）"],
  },
  {
    slug: "bolivia-heirloom",
    name_ja: "ボリビア在来種",
    category: "cultivar",
    group: "regional-heirloom",
    summary: "ボリビア・カラナビ等に残る在来品種。独特のフローラルな香り",
    description:
      "ボリビア在来の伝統品種で、カラナビなどに残る在来品種は独特のフローラルな香りで知られます。高標高と在来種の保存が品質の源泉です。",
    characteristics: [
      "在来集団",
      "高標高栽培",
      "保存活動が活発",
      "繊細でフルーティー",
    ],
    flavor_notes: ["フローラル", "フルーティー", "紅茶", "シトラス"],
    parent_lineage: "Typica / Bourbon 系在来集団",
    regions: ["ボリビア"],
    aliases: ["ボリビア在来種"],
  },
  {
    slug: "mbirizi",
    name_ja: "Mbirizi",
    category: "cultivar",
    group: "regional-heirloom",
    summary: "ルワンダ・ブルンジの在来系統。Bourbon 系に関連",
    description:
      "ルワンダ・ブルンジで見られる在来系統で、Bourbon Mayaguez と共通の品種群として栽培されています。復興プログラムで再評価されました。",
    characteristics: [
      "在来系統",
      "病害耐性あり",
      "ルワンダ復興プログラムで再評価",
      "ベリーと紅茶の繊細さ",
    ],
    flavor_notes: ["ベリー", "紅茶", "シトラス", "キャラメル"],
    parent_lineage: "Bourbon 系在来",
    regions: ["ルワンダ", "ブルンジ"],
    aliases: ["Mbirizi"],
  },
  {
    slug: "nyasaland",
    name_ja: "Nyasaland",
    category: "cultivar",
    group: "regional-heirloom",
    summary: "ウガンダ・ルウェンゾリ地区の在来系統",
    description:
      "ウガンダ・ルウェンゾリ地区で見られる在来系統です。SL 系統開発以前からの伝統栽培が残る地域で見られます。",
    characteristics: [
      "在来系統",
      "高標高に適応",
      "伝統栽培",
      "個性は地域により異なる",
    ],
    flavor_notes: ["ベリー", "シトラス", "紅茶"],
    parent_lineage: "Typica / Bourbon 系在来",
    regions: ["ウガンダ"],
    aliases: ["Nyasaland"],
  },
  {
    slug: "neshe-kentu",
    name_ja: "ネシェ・ケントゥ（Neshe Kentu）",
    category: "cultivar",
    group: "regional-heirloom",
    summary: "タンザニア在来の選抜品種。マイルドでバランスの良い風味",
    description:
      "タンザニアで栽培される在来選抜系統の一つです。SL28 などとは別系統の伝統品種として、マイルドでバランスの取れた杯質が期待できます。",
    characteristics: [
      "タンザニア在来選抜",
      "マイルドな杯質",
      "伝統栽培",
      "地域により個性が異なる",
    ],
    flavor_notes: ["ベリー", "シトラス", "紅茶", "バランス"],
    parent_lineage: "タンザニア在来集団",
    regions: ["タンザニア"],
    aliases: ["ネシェ・ケントゥ（Neshe Kentu）"],
  },
  {
    slug: "kp423",
    name_ja: "KP423",
    category: "cultivar",
    group: "kenya",
    summary: "タンザニアで栽培される選抜系統。SL 系統と並ぶ高品質品種",
    description:
      "タンザニアのコーヒー研究所で開発・選抜された系統の一つで、SL28 と並んで高品質な酸味とボディが期待できる品種として知られます。",
    characteristics: [
      "タンザニア開発・選抜系統",
      "高標高に適応",
      "SL 系統と並ぶ品質",
      "病害に感受性",
    ],
    flavor_notes: ["ベリー", "シトラス", "紅茶", "明るい酸味"],
    parent_lineage: "Scott Labs 系統に関連",
    regions: ["タンザニア"],
    aliases: ["KP423"],
  },
  {
    slug: "conilon",
    name_ja: "コンイロン（Conilon）",
    category: "cultivar",
    group: "robusta-cultivar",
    summary: "ブラジルで栽培されるロブスタ系品種。エスプレッソのコク強化に",
    description:
      "コンイロンはブラジルで Canephora（ロブスタ）の栽培品種として知られる名称です。エスプレッソのクレマ形成やコクの強化、インスタントコーヒー向けに使われます。",
    characteristics: [
      "ロブスタ（Canephora）系",
      "低地でも栽培可能",
      "高収量・病害に強い",
      "アラビカとのブレンド用",
    ],
    flavor_notes: ["ビター", "コク", "ナッツ", "穀物", "ダークチョコ"],
    parent_lineage: "Coffea canephora",
    regions: ["ブラジル", "ベトナム"],
    aliases: ["コンイロン（Robusta）"],
  },
  {
    slug: "tr4-tr9",
    name_ja: "TR4・TR9 など（ロブスタ系）",
    category: "cultivar",
    group: "robusta-cultivar",
    summary: "ベトナム開発のロブスタ品種。収量と病害耐性を重視",
    description:
      "ベトナム咖啡・カカオ研究所（WCR）などで開発されたロブスタ品種群です。TR4・TR9 などが代表例で、世界最大のロブスタ生産国ベトナムの主力となっています。",
    characteristics: [
      "ロブスタ（Canephora）系",
      "高収量・病害耐性",
      "低地大規模栽培向き",
      "インスタント・ブレンド向け",
    ],
    flavor_notes: ["ビター", "コク", "穀物", "ナッツ"],
    parent_lineage: "Coffea canephora 選抜",
    regions: ["ベトナム"],
    aliases: ["TR4・TR9 など"],
  },
];

export const VARIETY_GUIDES: VarietyGuide[] = [...speciesAndType, ...cultivars];
